name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1
  
dependencies:
  flutter_slidable: ^3.1.1
  flutter:
    sdk: flutter
  back_button_interceptor: ^7.0.3
  flutter_colorpicker: ^1.0.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
